### ISSUE TITLE
Composite Keys Not Saving with SQL Server 2014

### ISSUE THREAD

**Issue by gbenedict** [composite-primary-keys/composite_primary_keys#224]
I have a table with composite key made up of three fields.  When I attempt to save the record, it is failing.

```
2.1.2 :022 > user_role = UserRole.new(:VLSUserId => 1000, PartnerId: 1001, RoleId: 1002)
 => #<UserRole VLSUserId: 1000, RoleId: 1002, PartnerId: 1001> 

2.1.2 :023 > user_role.save
TinyTds::Error: Invalid column name 'RoleId'.: EXEC sp_executesql N'INSERT INTO [VLSUserRole] ([PartnerId], [RoleId], [VLSUserId]) OUTPUT inserted.VLSUserId,RoleId,PartnerId VALUES (@0, @1, @2)', N'@0 int, @1 int, @2 int', @0 = 1001, @1 = 1002, @2 = 1000
```

I believe the issue stems from [line 301 in the SQL Server adapter](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/eaced2841bd91301fecec1f7f0b7e2ab5d1b4327/lib/active_record/connection_adapters/sqlserver/database_statements.rb#L301):

```
        def sql_for_insert(sql, pk, id_value, sequence_name, binds)
          sql =
            if pk
              sql.insert(sql.index(/ (DEFAULT )?VALUES/), " OUTPUT inserted.#{pk}")
            else
              "#{sql}; SELECT CAST(SCOPE_IDENTITY() AS bigint) AS Ident"
            end
          super
        end
```

The `OUTPUT` portion is specified incorrectly:

```
EXEC sp_executesql N'INSERT INTO [VLSUserRole] (PartnerId, RoleId, VLSUserId) OUTPUT inserted.VLSUserId,RoleId,PartnerId VALUES (@0, @1, @2)', N'@0 int, @1 int, @2 int', @0 = 1000, @1 = 1002, @2 = 1001
```

It should be:

```
EXEC sp_executesql N'INSERT INTO [VLSUserRole] (PartnerId, RoleId, VLSUserId) OUTPUT inserted.VLSUserId, inserted.RoleId, inserted.PartnerId VALUES (@0, @1, @2)', N'@0 int, @1 int, @2 int', @0 = 1000, @1 = 1002, @2 = 1001
```

When this change is made the insert works.

For reference, here is the relevant part of my Gemfile:

```
gem 'rails', '4.1.4'
# Use sql server as the database for Active Record
gem 'tiny_tds'
# gem 'activerecord-sqlserver-adapter', '~> 4.1.0'
gem 'activerecord-sqlserver-adapter', git: 'https://github.com/vparihar01/activerecord-sqlserver-adapter.git'
gem 'composite_primary_keys', '~> 7.0.4'
```

**Comment by metaskills** [comment]
Thanks everyone for filing this issue. But this really belongs in the composite-primary-keys project. They [monkey patch](https://github.com/composite-primary-keys/composite_primary_keys/blob/master/lib/composite_primary_keys/connection_adapters/postgresql_adapter.rb#L21-L33) the same method `sql_for_insert` for PostgreSQL and they should add the same monkey patch to this adapter.

**Comment by cfis** [comment]
Yes, happy to apply a patch in CPK.

**Comment by jmozmoz** [comment]
Commit 79ae7f5bfcf6ee43627c21633bf15c8242968e69 should fix the problem for activerecord 4.1. At the moment, I do not know if the fix is necessary for activerecord-sqlserver-adapter 4.2.x, because I cannot test with MS SQL Server >=12.0

**Comment by cfis** [comment]
Thanks, second version applied.

**Comment by tommyalvarez** [comment]
@cfis @jmozmoz i'm still having the issue for: 
- composite_primary_keys "9.0.8" 
- activerecord_sqlserver_adapter "5.0.7"
- activerecord "5.0.2"

In the log during an insert the following error happens:

`#<ActiveRecord::StatementInvalid: TinyTds::Error: Invalid column name 'formula,producto'.: EXEC sp_executesql N'INSERT INTO [ProdFrm_Costos] ([formula], [producto], [codunidad], [descunidad], [costototal], [costocomponentes], [costorrhh], [costomaq], [costoindirecto], [fechamodif], [respmodif], [sbart_codgen], [sbart_codele1], [sbart_codele2], [sbart_codele3]) OUTPUT INSERTED.[formula,producto] VALUES (@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14)', N'@0 varchar(32), @1 varchar(41), @2 varchar(2), @3 varchar(6), @4 float, @5 float, @6 float, @7 float, @8 float, @9 datetime, @10 varchar(15), @11 varchar(20), @12 varchar(6), @13 varchar(6), @14 varchar(6)', @0 = 'F1-501600090000', @1 = '50160009-0000', @2 = 'UN', @3 = 'UN', @4 = 0.0, @5 = 0.0, @6 = 0.0, @7 = 0.0, @8 = 0.0, @9 = '01-15-2018 12:45:11.33', @10 = 'ADMIN', @11 = '50160009', @12 = '0000', @13 = '', @14 = ''>`

Am i missing something ? How can i fix this?

**Comment by tommyalvarez** [comment]
Found the issue @jmozmoz @cfis, i think. In my activerecord_sqlserver_adapter "5.0.7" ... the method 
`def sql_for_insert`
inherits from the following module chain:

```
module ActiveRecord
  module ConnectionAdapters
    module SQLServer
      module DatabaseStatements
```

while in this issue the patch applied is for the following module chain:

```
module ActiveRecord
  module ConnectionAdapters
    class SQLServerAdapter
```

This it is not monkeypatching correctly. I will monkey patch myself but the issue seems to be with incompatibility withing activerecord_sqlserver_adapter 5.0.7 and composite_primary_keys 9.0.7, on ruby 2.4.2 and activerecord 5.0.1 or 5.0.2

Regards
Tomas

**Comment by ElwoodBermuda** [comment]
This issues exists as well in the:
Version 10.x is designed to work with ActiveRecord 5.1.x
Composite keys has 
module ActiveRecord
  module ConnectionAdapters
    class SQLServerAdapter
and the active record has:
module ActiveRecord
  module ConnectionAdapters
    module SQLServer
      module DatabaseStatements

**Comment by cfis** [comment]
Would it be possible to submit a patch to fix?

Can you reproduce using the CPK test suite?

**Comment by cfis** [comment]
Ok, I've installed SQL server and cannot reproduce this on master (rails 6). So going to close this.
