### ISSUE TITLE
Can't clear query_cache in mysql

### ISSUE THREAD

**Issue by ta1kt0me** [composite-primary-keys/composite_primary_keys#539]
## What is problem

1. Find a record which is not still created.
2. Create the record.
3. Find it again, but it returns nil becuase of query cache of the first step.

This is now caused by a change in object hierarchy at https://github.com/composite-primary-keys/composite_primary_keys/commit/cf82cef70a7b92705dce5b5302c0f742408be794.

[When ActiveRecord::ConnectionAdapters::QueryCache is included, The defined dynamic method should clear the query cache](https://github.com/rails/rails/blob/v6.0.3.4/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb#L9-L26), but due to a change in the hierarchy, this process is no longer reached.

### Environment

- ruby 2.7.2
- rails 6.0.3.4
- composite_primary_keys 12.0.6

### Reproduction Step

1. create database `activerecord_unittest` in mysql
2. execute the bellow script like `ruby reproduce.rb`

```reproduce.rb
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activerecord", "6.0.3.4"
  gem "mysql2", "0.5.3"
  gem "composite_primary_keys", "12.0.6"
end

require "active_record"
require "minitest/autorun"
require "logger"

# before create database in mysql
# ```sql
# create database activerecord_unittest;
# ```
config = {
  primary: {
	adapter: "mysql2",
	username: "root",
	database: "activerecord_unittest"
  }
}

ActiveRecord::Base.configurations = config
resolver = ActiveRecord::ConnectionAdapters::ConnectionSpecification::Resolver.new(ActiveRecord::Base.configurations)
spec = resolver.spec(:primary)
ActiveRecord::Base.establish_connection(spec.to_hash)
ActiveRecord::Base.connection_handlers = {
  writing: ActiveRecord::Base.default_connection_handler
}

ActiveRecord::Base.logger = Logger.new($stdout)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
	t.string :title
	t.string :genre
  end
end

class Post < ActiveRecord::Base
  self.primary_keys = :title, :genre
end

class QueryCacheTest < Minitest::Test
  def test_clear_query_cache
	Post.cache do
	  title = "new title"
	  no_created_post = Post.find_by(title: title) # create query_cache
	  Post.create!(title: title, genre: "sf") # clear query_cache by ActiveRecord::ConnectionHandling#clear_query_caches_for_current_thread
	  created_post = Post.find_by(title: title) # Don't use query_cache

	  assert_nil no_created_post
	  assert_equal created_post.title, title # raise NoMethodError: undefined method `title' for nil:NilClass
	end
  end
end

```

output in my development environment,

```
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using concurrent-ruby 1.1.7
Using i18n 1.8.7
Using minitest 5.14.3
Using thread_safe 0.3.6
Using tzinfo 1.2.9
Using zeitwerk 2.4.2
Using activesupport 6.0.3.4
Using activemodel 6.0.3.4
Using activerecord 6.0.3.4
Using bundler 2.1.4
Using composite_primary_keys 12.0.6
Using mysql2 0.5.3
-- create_table(:posts, {:force=>true})
D, [2021-01-18T23:26:41.946914 #87075] DEBUG -- :    (0.3ms)  SET  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
D, [2021-01-18T23:26:41.977522 #87075] DEBUG -- :    (30.0ms)  DROP TABLE IF EXISTS `posts`
D, [2021-01-18T23:26:42.027573 #87075] DEBUG -- :    (49.5ms)  CREATE TABLE `posts` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `title` varchar(255), `genre` varchar(255))
   -> 0.0838s
D, [2021-01-18T23:26:42.052620 #87075] DEBUG -- :   ActiveRecord::InternalMetadata Load (0.2ms)  SELECT `ar_internal_metadata`.* FROM `ar_internal_metadata` WHERE `ar_internal_metadata`.`key` = 'environment' LIMIT 1
Run options: --seed 18037

# Running:

D, [2021-01-18T23:26:42.064008 #87075] DEBUG -- :   Post Load (0.2ms)  SELECT `posts`.* FROM `posts` WHERE `posts`.`title` = 'new title' LIMIT 1
D, [2021-01-18T23:26:42.067024 #87075] DEBUG -- :    (0.1ms)  BEGIN
D, [2021-01-18T23:26:42.067315 #87075] DEBUG -- :   Post Create (0.2ms)  INSERT INTO `posts` (`title`, `genre`) VALUES ('new title', 'sf')
D, [2021-01-18T23:26:42.090523 #87075] DEBUG -- :    (22.3ms)  COMMIT
D, [2021-01-18T23:26:42.091079 #87075] DEBUG -- :   CACHE Post Load (0.0ms)  SELECT `posts`.* FROM `posts` WHERE `posts`.`title` = 'new title' LIMIT 1  [["title", "new title"], ["LIMIT", 1]]
E

Finished in 0.030117s, 33.2038 runs/s, 33.2038 assertions/s.

  1) Error:
QueryCacheTest#test_clear_query_cache:
NoMethodError: undefined method `title' for nil:NilClass
    ar.rb:58:in `block in test_clear_query_cache'
    /Users/greg/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/query_cache.rb:61:in `cache'
    /Users/greg/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/query_cache.rb:11:in `cache'
    ar.rb:51:in `test_clear_query_cache'

1 runs, 1 assertions, 0 failures, 1 errors, 0 skips
```

## Workaround

```rb
# Add the below code in the end of above reproduction script or config/initializers/*.rb in Rails app
module PatchForClearingQueryCache
  def insert(*)
    ActiveRecord::Base.clear_query_caches_for_current_thread if @query_cache_enabled
    super
  end
end

ActiveRecord::ConnectionAdapters::Mysql2Adapter.prepend(PatchForClearingQueryCache)
```

**Comment by cfis** [comment]
Thanks for the detailed report - will take a look!

**Comment by cfis** [comment]
I couldn't actually create a test to duplicate the issue (I followed your very good example). But I do believe its fixed. Issue was CPK first needs to load the mysql database adapter before overriding it, otherwise the inheritance hierarchy is incorrect.

Thanks for the report and detailed information!

**Comment by ta1kt0me** [comment]
Thank you so much for your fix! I’ve confirm the problem is resolved.

**Comment by cfis** [comment]
Could you test 12.0.8? I realized that I mistakenly commented out the original MySQL fix and then reimplemented again.

So just want to make sure this issue remains fixed in 12.0.8

**Comment by ta1kt0me** [comment]
@cfis I've tested 12.0.8 and confirmed that the issue exists again. Could you reopen this issue?

**Comment by cfis** [comment]
Oh - interesting. Reopening.

**Comment by cfis** [comment]
Ok this is hopefully solved once and for all.
